services:
  - postgres
  - redis

stages:
  - test
  - deploy

variables:
  DATABASE_URL: "postgres://postgres:postgres@postgres/codelabs_test"
  REDIS_URL: "redis://redis/"
  APPLICATION_URL: "http://localhost/"
  SMTP_FROM: "codelabs@codelabs.local"

test:
  environment: test
  stage: test
  script:
    - gem update --system
    - gem update bundler --force
    - bundle config set path 'vendor/ruby'
    - bundle install
    - RAILS_ENV=test bundle exec rake db:create
    - RAILS_ENV=test bundle exec rake db:schema:load
    - bundle exec rake
  cache:
    paths:
      - vendor/ruby


deploy_staging:
  image: ruby:alpine
  environment: development
  stage: deploy
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - gem install capistrano capistrano-rails
    - cap staging deploy
  only:
    - master

deploy_production:
  image: ruby:alpine
  environment: production
  stage: deploy
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - gem install capistrano capistrano-rails
    - cap production deploy
  only:
    - production
