deploy_staging:
  environment: development
  stage: deploy
  script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - ssh-add <(echo -e "$SSH_PRIVATE_KEY")
    - gem install capistrano capistrano-rbenv capistrano-rails
    - cap staging deploy
  only:
    - master
