deploy_staging:
  image: ruby:alpine
  environment: development
  stage: deploy
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo -e "$SSH_PRIVATE_KEY" > key
    - chmod 400 key
    - ssh-add key
    - gem install capistrano capistrano-rails
    - cap staging deploy
    - rm key
  only:
    - master

deploy_production:
  image: ruby:alpine
  environment: production
  stage: deploy
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo -e "$SSH_PRIVATE_KEY" > key
    - chmod 400 key
    - ssh-add key
    - gem install capistrano capistrano-rails
    - cap production deploy
    - rm key
  only:
    - production
