name: Brakeman Scan

on:
  pull_request:
    branches: [ master, production ]

jobs:
  brakeman-scan:
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.0.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.5
          bundler-cache: true

      - name: Scan
        continue-on-error: true
        run: bundle exec brakeman -f sarif -o brakeman.sarif.json .

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: brakeman.sarif.json
