name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://stage.codelabs.site
    env:
      BUNDLE_GEMFILE: Gemfile.deploy
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v3
      - name: Set up Ruby 2.7.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true

      - name: Deploy
        run: bundle exec cap staging deploy
