name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://stage.codelabs.site
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v4
      - name: Set up Ruby 3.0.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.5
          bundler-cache: true

      - name: Deploy
        run: bundle exec cap staging deploy
